<a href="https://colab.research.google.com/github/Pedja1201/ModelovanjeSoftvera-AstahProfesional-/blob/main/NumPy_Upoznavanje.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Upoznavanje sa NumPy**

In [3]:
import numpy as np #Uvoz biblioteke

**Arrays(Nizovi)**

In [4]:
#Kreiranje niza
a=np.array([0,1,2])

In [5]:
a

array([0, 1, 2])

In [6]:
a.shape  #3 elementa u jednoj dimenziji(Racuna elemente)

(3,)

In [7]:
a.ndim

1

In [8]:
a.size #Duzina niza

3

In [9]:
print([0])

[0]


**Kreiranje 2 dimenzionih nizova**

In [11]:
x2=np.random.randint(10,size=(3,4))

In [12]:
x2


array([[8, 0, 2, 8],
       [3, 4, 2, 0],
       [5, 6, 2, 8]])

In [14]:
x2[2,-1]

8

x(start:stop:step) default value start=0, stop=size of dimensions, step=1

In [15]:
x=np.arange(10)

In [16]:
x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x[:5]

array([0, 1, 2, 3, 4])

In [18]:
x[5:] #Od 5 pa do kraja

array([5, 6, 7, 8, 9])

In [19]:
x[4:7]  #Od 4 do 7

array([4, 5, 6])

In [20]:
x[::2] #svaki drugi(step)

array([0, 2, 4, 6, 8])

In [21]:
x[::-1] #Citanje niza sa suprotne strane

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [23]:
x[5::-2] #Svaki drugi od pozadi

array([5, 3, 1])

In [24]:
x2


array([[8, 0, 2, 8],
       [3, 4, 2, 0],
       [5, 6, 2, 8]])

In [25]:
x2[:3, ::2] #Po prvoj dimenziji do 3, po drugoj svaki drugi

array([[8, 2],
       [3, 2],
       [5, 2]])

**Reshaping**

In [26]:
grid=np.arange(1,10).reshape(3,3)

In [27]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
x=np.array([1,2,3])

In [29]:
y=np.array([3,2,1])

In [30]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [34]:
xx=np.concatenate([grid, grid])

In [35]:
xx.shape

(6, 3)

In [36]:
xx=np.concatenate([grid, grid], axis=1)

In [37]:
xx.shape

(3, 6)

**Splitting**

In [39]:
x=np.arange(10)

In [40]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
x1,x2,x3=np.split(x,[3,5])

In [43]:
print(x1,x2,x3)

[0 1 2] [3 4] [5 6 7 8 9]


In [45]:
x1,x2=np.split(x,2)

In [46]:
print(x1,x2)

[0 1 2 3 4] [5 6 7 8 9]


**Array math**

In [47]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
grid+grid

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [49]:
grid-2*grid

array([[-1, -2, -3],
       [-4, -5, -6],
       [-7, -8, -9]])